build.gradle, src/main/java/com/example/weup/config/AwsS3Config.java, src/main/java/com/example/weup/constant/ErrorInfo.java, src/main/java/com/example/weup/controller/MemberController.java, src/main/java/com/example/weup/controller/ProjectController.java, src/main/java/com/example/weup/dto/request/DeleteMemberRequestDTO.java, src/main/java/com/example/weup/dto/request/DeleteRoleRequestDTO.java, src/main/java/com/example/weup/dto/request/EditRoleRequestDTO.java, src/main/java/com/example/weup/dto/request/LeaderDelegateRequestDTO.java, src/main/java/com/example/weup/dto/request/ProjectInviteRequestDTO.java, src/main/java/com/example/weup/dto/request/ProjectMemberRequestDTO.java, src/main/java/com/example/weup/dto/response/ListUpProjectResponseDTO.java, src/main/java/com/example/weup/dto/response/MemberInfoResponseDTO.java, src/main/java/com/example/weup/entity/AccountSocial.java, src/main/java/com/example/weup/entity/Member.java, src/main/java/com/example/weup/entity/MemberRole.java, src/main/java/com/example/weup/entity/Member_Role.java, src/main/java/com/example/weup/entity/Project.java, src/main/java/com/example/weup/entity/Role.java, src/main/java/com/example/weup/entity/User.java, src/main/java/com/example/weup/repository/MemberRepository.java, src/main/java/com/example/weup/repository/MemberRoleRepository.java, src/main/java/com/example/weup/repository/RoleRepository.java, src/main/java/com/example/weup/service/MailService.java, src/main/java/com/example/weup/service/MemberService.java, src/main/java/com/example/weup/service/ProjectService.java, src/main/resources/templates/InviteEmail.html
- Project Controller, Project Service 로직 수정
- Member_Role -> MemberRole로 수정
- Member Entity 필드 수정
- Member Service에 로직 추가
- MemberRepository에 로직 추가
=> Ended develop/project Logic

build.gradle, src/main/java/com/example/weup/config/WebSocketConfig.java, src/main/java/com/example/weup/constant/ErrorInfo.java, src/main/java/com/example/weup/controller/ChatController.java, src/main/java/com/example/weup/controller/ScheduleController.java, src/main/java/com/example/weup/dto/request/ChatMessageRequestDto.java, src/main/java/com/example/weup/dto/request/EditScheduleRequestDTO.java, src/main/java/com/example/weup/dto/response/ChatMessageResponseDto.java, src/main/java/com/example/weup/entity/ChatMessage.java, src/main/java/com/example/weup/entity/ChatRoom.java, src/main/java/com/example/weup/entity/Member.java, src/main/java/com/example/weup/repository/ChatMessageRepository.java, src/main/java/com/example/weup/repository/ChatRoomRepository.java, src/main/java/com/example/weup/service/ChatService.java, src/main/java/com/example/weup/service/ProjectService.java, src/main/java/com/example/weup/service/ScheduleService.java
chat 기능 안에 있는 WebSocket 연결을 테스트해보지 못해서 WebRTC 브랜치와 Schedule 브랜치를 모두 Chat 브랜치로 병합함.
=> develop/webrtc merge to develop/chat

src/main/java/com/example/weup/WeUpApplication.java, src/main/java/com/example/weup/controller/ChatController.java, src/main/java/com/example/weup/repository/ChatMessageRepository.java, src/main/java/com/example/weup/service/ChatService.java, src/main/resources/application.properties
=> edit get chat messages logic, etc...  #28

src/main/java/com/example/weup/controller/TodoController.java, src/main/java/com/example/weup/dto/request/CreateTodoRequestDTO.java, src/main/java/com/example/weup/dto/request/EditTodoRequestDTO.java, src/main/java/com/example/weup/dto/request/EditTodoStatusRequestDTO.java, src/main/java/com/example/weup/entity/Todo.java, src/main/java/com/example/weup/service/TodoService.java
=> [FIX] 투두 생성 로직 수정

src/main/java/com/example/weup/repository/TodoMemberRepository.java, src/main/java/com/example/weup/service/TodoService.java
투두 담당자 수정 시 삭제 후 추가하는 로직 상에서
삭제 후 데이터베이스 조회를 통해 실제로 삭제된 다음 추가되도록 수정
=> [FIX] 투두 수정 로직 수정

src/main/java/com/example/weup/controller/BoardController.java, src/main/java/com/example/weup/dto/request/BoardCreateRequestDTO.java, src/main/java/com/example/weup/entity/File.java, src/main/java/com/example/weup/service/BoardService.java
projectId를 DTO에 담아 보내지 않고
@PathVariable로 전달하게끔 수정
=> [FIX] 게시판 생성 로직 수정

src/main/java/com/example/weup/controller/ChatController.java, src/main/java/com/example/weup/service/BoardService.java, src/main/java/com/example/weup/service/ChatService.java
게시글 상세 정보 및 채팅 불러오기 시
프로필 이미지가 presignedURL로 제대로 가져오지 못하던 오류 수정
=> modify getting profile_image logic

src/main/java/com/example/weup/controller/AiChatController.java, src/main/java/com/example/weup/dto/request/AiRoleAssignRequestDTO.java, src/main/java/com/example/weup/dto/request/AiTodoCreateRequestDTO.java, src/main/java/com/example/weup/repository/MemberRepository.java, src/main/java/com/example/weup/service/AiChatService.java
AI 서버에서 백엔드로 요청 보내는 API 2개 코드 추가 및 수정
=> Merge ai-role-assign to dev

src/main/java/com/example/weup/config/ExceptionHandlers.java, src/main/java/com/example/weup/controller/BoardController.java, src/main/java/com/example/weup/dto/request/BoardCreateRequestDTO.java, src/main/java/com/example/weup/dto/request/EditBoardRequestDTO.java, src/main/java/com/example/weup/dto/response/BoardListResponseDTO.java, src/main/java/com/example/weup/dto/response/FileResponseDTO.java, src/main/java/com/example/weup/service/BoardService.java
- projectId @PathVariable이 아니라 DTO로
- Null값 처리 제목, 태그만
- 제목, 내용에 trim() 적용
- nickName -> name으로 수정
- file 리스트에 fileId 추가 - 수정 시 사용
- Null값 처리 제목, 태그만
- 파일 수정 로직 변경 - removeFileIds 필드 추가하여 삭제할 파일 리스트, 추가할 파일 리스트 따로 받기
=> Modify & Refactor board logic

src/main/java/com/example/weup/service/MemberService.java
Member List 반환 시 IsLeader 필드가 항상 false로 반환되던 오류 수정
=> modify member list - isLeader()

src/main/java/com/example/weup/security/JwtFilter.java, src/main/java/com/example/weup/security/exception/JwtAuthenticationEntryPoint.java
JWTFilter에서 토큰이 없거나 만료되었음을 감지 시
throw로 예외를 던지면 DispatcherServlet으로 감
이렇게 하지 말고 jwtAuthenticationEntryPoint.commence()를 사용하여
Spring Security 인증 실패 진입점으로 직접 위임
=> modify JWT token exception logic

src/main/java/com/example/weup/controller/MemberController.java, src/main/java/com/example/weup/service/MemberService.java
멤버 삭제 시 컨트롤러 to 서비스로 DTO를 넘기게끔 수정
- 지난 수정 시 반영되지 않았던 것처럼 보임
=> 리팩터링 - 멤버 삭제 매개변수 수정

src/main/java/com/example/weup/config/SecurityConfig.java, src/main/resources/application-prod.properties
=> CORS 주소 변경

src/main/java/com/example/weup/controller/LiveKitController.java
Https 설정 때문에 테스트는 못했지만 우선 Dev에 Merge
=> [FIX] Merge Issue #82 to Dev

src/main/java/com/example/weup/config/SecurityConfig.java, src/main/java/com/example/weup/config/StompChannelInterceptor.java, src/main/java/com/example/weup/config/StompEventListener.java, src/main/java/com/example/weup/config/WebSocketConfig.java, src/main/java/com/example/weup/constant/ErrorInfo.java, src/main/java/com/example/weup/constant/SenderType.java, src/main/java/com/example/weup/controller/ChatController.java, src/main/java/com/example/weup/controller/UserController.java, src/main/java/com/example/weup/dto/request/CreateChatRoomDTO.java, src/main/java/com/example/weup/dto/request/InviteChatRoomDTO.java, src/main/java/com/example/weup/dto/request/SendMessageRequestDTO.java, src/main/java/com/example/weup/dto/request/SignInRequestDTO.java, src/main/java/com/example/weup/dto/request/SignUpRequestDTO.java, src/main/java/com/example/weup/dto/response/GetChatRoomListDTO.java, src/main/java/com/example/weup/dto/response/ReceiveMessageResponseDto.java, src/main/java/com/example/weup/entity/ChatMessage.java, src/main/java/com/example/weup/entity/ChatRoom.java, src/main/java/com/example/weup/entity/ChatRoomMember.java, src/main/java/com/example/weup/repository/ChatRoomMemberRepository.java, src/main/java/com/example/weup/security/JwtFilter.java, src/main/java/com/example/weup/security/JwtSignInAuthenticationFilter.java, src/main/java/com/example/weup/service/AiChatService.java, src/main/java/com/example/weup/service/ChatService.java, src/main/java/com/example/weup/service/SessionService.java, src/main/java/com/example/weup/service/UserService.java, src/main/java/com/example/weup/validate/MemberValidator.java
브랜치 분기를 위해 dev 브랜치로 일시적인 merge 수행
=> Temporary merge to dev

src/main/java/com/example/weup/controller/ChatController.java, src/main/java/com/example/weup/service/ChatService.java, src/main/java/com/example/weup/validate/MemberValidator.java
=> FIX: Chat logic Extension #92

src/main/java/com/example/weup/controller/ChatController.java, src/main/java/com/example/weup/dto/request/EditChatRoomNameRequestDTO.java, src/main/java/com/example/weup/dto/response/GetChatRoomListDTO.java, src/main/java/com/example/weup/dto/response/GetInvitableListDTO.java, src/main/java/com/example/weup/entity/ChatMessage.java, src/main/java/com/example/weup/entity/ChatRoom.java, src/main/java/com/example/weup/repository/ChatMessageRepository.java, src/main/java/com/example/weup/security/JwtSignInAuthenticationFilter.java, src/main/java/com/example/weup/service/ChatService.java, src/main/java/com/example/weup/service/MemberService.java, src/main/java/com/example/weup/service/UserService.java
ChatController @loginuser user->userId로 수정
채팅방 생성 시 초대한 인원도 참여되게끔 수정
ChatRoom의 project 연결 @manytoone으로 수정
createChatRoom basic이 false로 생성되게 변경
채팅 초대 가능 인원 목록 불러오기 경로 수정
채팅 리스트 불러오기 반환값에 isBasic 추가 (기본 채팅방은 수정을 막기 위해)
채팅방 이름 수정 시에 dto에 담아 보내게끔 수정
=> FIX: chat logic extension

src/main/java/com/example/weup/config/StompChannelInterceptor.java, src/main/java/com/example/weup/dto/response/ReceiveMessageResponseDTO.java, src/main/java/com/example/weup/dto/response/RedisMessageDTO.java, src/main/java/com/example/weup/entity/ChatMessage.java, src/main/java/com/example/weup/service/AiChatService.java, src/main/java/com/example/weup/service/ChatService.java, src/main/java/com/example/weup/service/MemberService.java
refactor: ai chat logic
fix: system chat sentat
save ai reply in db
npe prevention in setdisplaytype
=> FIX: Chat Logic Extension++ #111

src/main/java/com/example/weup/service/MemberService.java
=> [FIX] merge error in #127, MemberService

src/main/java/com/example/weup/controller/AiChatController.java, src/main/java/com/example/weup/entity/Member.java, src/main/java/com/example/weup/entity/User.java, src/main/java/com/example/weup/handler/StompChannelInterceptor.java, src/main/java/com/example/weup/service/AiChatService.java, src/main/java/com/example/weup/service/ChatService.java, src/main/java/com/example/weup/service/MemberService.java
AI가 Back-End 서버로 HTTP API 요청을 보낸 후 그에 대한 응답 값이 Front-End로 전달되지 않음. 아무런 답변도 전송되지 않아 사용자 입장에서는 어떤 일이 발생했는지 알 수 없음.
Entity에 Not Null이 빠진 부분이 있어서 수정함.
=> [FIX] AI Chat Message Response Type, Entity Type

src/main/java/com/example/weup/entity/ChatRoom.java, src/main/java/com/example/weup/entity/Todo.java, src/main/java/com/example/weup/service/ChatRoomService.java
- 투두 수정 시, 시작일과 마감일을 둘 다 지정하지 않고 하루만으로 지정하는 경우 제대로 수정되지 않던 오류 수정
- 기본 채팅방 이름 기본값 변경
=> [FIX] 0821 QA

src/main/java/com/example/weup/entity/Board.java, src/main/java/com/example/weup/entity/ChatMessage.java
=> [FIX] Entity Not Null

src/main/java/com/example/weup/constant/ErrorInfo.java, src/main/java/com/example/weup/dto/request/BoardCreateRequestDTO.java, src/main/java/com/example/weup/entity/Member.java, src/main/java/com/example/weup/repository/MemberRoleRepository.java, src/main/java/com/example/weup/repository/NotificationRepository.java, src/main/java/com/example/weup/service/BoardService.java, src/main/java/com/example/weup/service/MemberService.java, src/main/java/com/example/weup/service/TodoService.java, src/main/java/com/example/weup/service/UserService.java, src/main/resources/application-prod.properties
회원 탈퇴 → 테이블 매핑 관계
멤버 탈퇴 시 할당된 역할, 스케쥴 해제
실시간 처리 2번째부터 밀리는 문제
게시판 파일 크기 제한 50mb로 변경
게시글 작성 및 수정 시 파일, 내용 중 하나는 반드시 있게끔 변경
=> FIX: 0828 QA
